<?php

namespace rnadvanceemailingwc\TwigManager\Renderers\Blocks;

use rnadvanceemailingwc\DTO\ParagraphBlockOptionsDTO;
use rnadvanceemailingwc\TwigManager\Renderers\Blocks\Core\BlockRendererBase;
use rnadvanceemailingwc\TwigManager\TextRenderer\DocumentTextRenderer;

class ParagraphBlockRenderer extends BlockRendererBase
{
    /** @var ParagraphBlockOptionsDTO */
    public $Options;
    /** @var DocumentTextRenderer */
    public $Document;
    public $Text;
    public function __construct($options, $parent = null)
    {
        parent::__construct($options, $parent);
        $this->Document=new DocumentTextRenderer($this->Options->Content,$this);
    }


    protected function GetTemplateName()
    {
        return 'TwigManager/Renderers/Blocks/ParagraphBlockRenderer.twig';
    }

    protected function InternalInitialize()
    {
        parent::InternalInitialize(); // TODO: Change the autogenerated stub
        $this->Document->Initialize();
        $this->Text=$this->Document->Render();
    }


}